[package]
name = "zad_1"
version = "0.1.0"
authors = ["sbaginsk <szymon.baginski@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openssl = "0.10.23"
